### ISSUE TITLE
Encode initial RESOLUTE semantics in Coq

### ISSUE THREAD

**Issue by ampetz** [ku-sldg/resolute-copland#8]
Encode the RESOLUTE inference rule semantics (Figure 8 from: [here](https://arxiv.org/pdf/1409.4629)) in Coq.

Initial spec can go:  [here](https://github.com/ku-sldg/resolute-copland/blob/main/src/Resolute_Logic.v)

**Comment by Durbatuluk1701** [comment]
Here is an example of operational semantics for a Type system in coq https://softwarefoundations.cis.upenn.edu/plf-current/Types.html#lab186, not quite the same but it should give some idea of how to convert inference rules to coq spec
